project_id = "yufifhkmybiasnzmjgsk"

[functions.generate-sign-assets]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.daily-summary]
verify_jwt = false